---

###########
# Removed #
###########

manala_deploy_removed:
  - web/app_dev.php
  - web/app_test.php

#########
# Tasks #
#########

manala_deploy_tasks:
  - make: install@production
  - make: build@production
