---

#######
# Dir #
#######

manala_deploy_dir: /srv/app

############
# Releases #
############

manala_deploy_releases: 5

############
# Strategy #
############

manala_deploy_strategy: git

manala_deploy_strategy_git_repo:    git@github.com:vendor/app.git
manala_deploy_strategy_git_version: master

##########
# Copied #
##########

manala_deploy_copied:
  - vendor

##########
# Shared #
##########

manala_deploy_shared_files:
  - app/config/parameters.yml

manala_deploy_shared_dirs:
  - var/logs
  - var/sessions

############
# Writable #
############

#manala_deploy_writable_dirs_default:
#  mode:   ug=rwx,o=rx
#  follow: true
#manala_deploy_writable_dirs:
#  - var/cache
#  - var/logs
#  - var/sessions
